/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetPasswordRouteImport } from './routes/set-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppVaultOverviewRouteImport } from './routes/app.vault-overview'
import { Route as AppVaultRouteImport } from './routes/app.vault'
import { Route as AppTeamsRouteImport } from './routes/app.teams'
import { Route as AppMeetingsRouteImport } from './routes/app.meetings'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppCompetitionsRouteImport } from './routes/app.competitions'
import { Route as AppBacklogRouteImport } from './routes/app.backlog'
import { Route as AppAgreementRouteImport } from './routes/app.agreement'
import { Route as AppAdminRouteImport } from './routes/app.admin'
import { Route as AppTeamsTeamIdRouteImport } from './routes/app.teams.$teamId'
import { Route as AppAdminUsageRouteImport } from './routes/app.admin_.usage'
import { Route as AppAdminTeamReadinessIndexRouteImport } from './routes/app.admin_.team-readiness.index'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as AppAdminTeamReadinessTeamIdRouteImport } from './routes/app.admin_.team-readiness.$teamId'
import { Route as ApiPublicHooksWeeklyDigestRouteImport } from './routes/api/public/hooks/weekly-digest'
import { Route as ApiPublicHooksProfileRemindersRouteImport } from './routes/api/public/hooks/profile-reminders'
import { Route as ApiPublicHooksAutoArchiveRouteImport } from './routes/api/public/hooks/auto-archive'

const SetPasswordRoute = SetPasswordRouteImport.update({
  id: '/set-password',
  path: '/set-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVaultOverviewRoute = AppVaultOverviewRouteImport.update({
  id: '/vault-overview',
  path: '/vault-overview',
  getParentRoute: () => AppRoute,
} as any)
const AppVaultRoute = AppVaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamsRoute = AppTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => AppRoute,
} as any)
const AppMeetingsRoute = AppMeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCompetitionsRoute = AppCompetitionsRouteImport.update({
  id: '/competitions',
  path: '/competitions',
  getParentRoute: () => AppRoute,
} as any)
const AppBacklogRoute = AppBacklogRouteImport.update({
  id: '/backlog',
  path: '/backlog',
  getParentRoute: () => AppRoute,
} as any)
const AppAgreementRoute = AppAgreementRouteImport.update({
  id: '/agreement',
  path: '/agreement',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamsTeamIdRoute = AppTeamsTeamIdRouteImport.update({
  id: '/$teamId',
  path: '/$teamId',
  getParentRoute: () => AppTeamsRoute,
} as any)
const AppAdminUsageRoute = AppAdminUsageRouteImport.update({
  id: '/admin_/usage',
  path: '/admin/usage',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminTeamReadinessIndexRoute =
  AppAdminTeamReadinessIndexRouteImport.update({
    id: '/admin_/team-readiness/',
    path: '/admin/team-readiness/',
    getParentRoute: () => AppRoute,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppAdminTeamReadinessTeamIdRoute =
  AppAdminTeamReadinessTeamIdRouteImport.update({
    id: '/admin_/team-readiness/$teamId',
    path: '/admin/team-readiness/$teamId',
    getParentRoute: () => AppRoute,
  } as any)
const ApiPublicHooksWeeklyDigestRoute =
  ApiPublicHooksWeeklyDigestRouteImport.update({
    id: '/api/public/hooks/weekly-digest',
    path: '/api/public/hooks/weekly-digest',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksProfileRemindersRoute =
  ApiPublicHooksProfileRemindersRouteImport.update({
    id: '/api/public/hooks/profile-reminders',
    path: '/api/public/hooks/profile-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAutoArchiveRoute =
  ApiPublicHooksAutoArchiveRouteImport.update({
    id: '/api/public/hooks/auto-archive',
    path: '/api/public/hooks/auto-archive',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/set-password': typeof SetPasswordRoute
  '/app/admin': typeof AppAdminRoute
  '/app/agreement': typeof AppAgreementRoute
  '/app/backlog': typeof AppBacklogRoute
  '/app/competitions': typeof AppCompetitionsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/meetings': typeof AppMeetingsRoute
  '/app/teams': typeof AppTeamsRouteWithChildren
  '/app/vault': typeof AppVaultRoute
  '/app/vault-overview': typeof AppVaultOverviewRoute
  '/app/admin/usage': typeof AppAdminUsageRoute
  '/app/teams/$teamId': typeof AppTeamsTeamIdRoute
  '/api/public/hooks/auto-archive': typeof ApiPublicHooksAutoArchiveRoute
  '/api/public/hooks/profile-reminders': typeof ApiPublicHooksProfileRemindersRoute
  '/api/public/hooks/weekly-digest': typeof ApiPublicHooksWeeklyDigestRoute
  '/app/admin/team-readiness/$teamId': typeof AppAdminTeamReadinessTeamIdRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/app/admin/team-readiness/': typeof AppAdminTeamReadinessIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/set-password': typeof SetPasswordRoute
  '/app/admin': typeof AppAdminRoute
  '/app/agreement': typeof AppAgreementRoute
  '/app/backlog': typeof AppBacklogRoute
  '/app/competitions': typeof AppCompetitionsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/meetings': typeof AppMeetingsRoute
  '/app/teams': typeof AppTeamsRouteWithChildren
  '/app/vault': typeof AppVaultRoute
  '/app/vault-overview': typeof AppVaultOverviewRoute
  '/app/admin/usage': typeof AppAdminUsageRoute
  '/app/teams/$teamId': typeof AppTeamsTeamIdRoute
  '/api/public/hooks/auto-archive': typeof ApiPublicHooksAutoArchiveRoute
  '/api/public/hooks/profile-reminders': typeof ApiPublicHooksProfileRemindersRoute
  '/api/public/hooks/weekly-digest': typeof ApiPublicHooksWeeklyDigestRoute
  '/app/admin/team-readiness/$teamId': typeof AppAdminTeamReadinessTeamIdRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/app/admin/team-readiness': typeof AppAdminTeamReadinessIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/set-password': typeof SetPasswordRoute
  '/app/admin': typeof AppAdminRoute
  '/app/agreement': typeof AppAgreementRoute
  '/app/backlog': typeof AppBacklogRoute
  '/app/competitions': typeof AppCompetitionsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/meetings': typeof AppMeetingsRoute
  '/app/teams': typeof AppTeamsRouteWithChildren
  '/app/vault': typeof AppVaultRoute
  '/app/vault-overview': typeof AppVaultOverviewRoute
  '/app/admin_/usage': typeof AppAdminUsageRoute
  '/app/teams/$teamId': typeof AppTeamsTeamIdRoute
  '/api/public/hooks/auto-archive': typeof ApiPublicHooksAutoArchiveRoute
  '/api/public/hooks/profile-reminders': typeof ApiPublicHooksProfileRemindersRoute
  '/api/public/hooks/weekly-digest': typeof ApiPublicHooksWeeklyDigestRoute
  '/app/admin_/team-readiness/$teamId': typeof AppAdminTeamReadinessTeamIdRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/app/admin_/team-readiness/': typeof AppAdminTeamReadinessIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/set-password'
    | '/app/admin'
    | '/app/agreement'
    | '/app/backlog'
    | '/app/competitions'
    | '/app/dashboard'
    | '/app/meetings'
    | '/app/teams'
    | '/app/vault'
    | '/app/vault-overview'
    | '/app/admin/usage'
    | '/app/teams/$teamId'
    | '/api/public/hooks/auto-archive'
    | '/api/public/hooks/profile-reminders'
    | '/api/public/hooks/weekly-digest'
    | '/app/admin/team-readiness/$teamId'
    | '/lovable/email/transactional/preview'
    | '/app/admin/team-readiness/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/login'
    | '/set-password'
    | '/app/admin'
    | '/app/agreement'
    | '/app/backlog'
    | '/app/competitions'
    | '/app/dashboard'
    | '/app/meetings'
    | '/app/teams'
    | '/app/vault'
    | '/app/vault-overview'
    | '/app/admin/usage'
    | '/app/teams/$teamId'
    | '/api/public/hooks/auto-archive'
    | '/api/public/hooks/profile-reminders'
    | '/api/public/hooks/weekly-digest'
    | '/app/admin/team-readiness/$teamId'
    | '/lovable/email/transactional/preview'
    | '/app/admin/team-readiness'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/set-password'
    | '/app/admin'
    | '/app/agreement'
    | '/app/backlog'
    | '/app/competitions'
    | '/app/dashboard'
    | '/app/meetings'
    | '/app/teams'
    | '/app/vault'
    | '/app/vault-overview'
    | '/app/admin_/usage'
    | '/app/teams/$teamId'
    | '/api/public/hooks/auto-archive'
    | '/api/public/hooks/profile-reminders'
    | '/api/public/hooks/weekly-digest'
    | '/app/admin_/team-readiness/$teamId'
    | '/lovable/email/transactional/preview'
    | '/app/admin_/team-readiness/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SetPasswordRoute: typeof SetPasswordRoute
  ApiPublicHooksAutoArchiveRoute: typeof ApiPublicHooksAutoArchiveRoute
  ApiPublicHooksProfileRemindersRoute: typeof ApiPublicHooksProfileRemindersRoute
  ApiPublicHooksWeeklyDigestRoute: typeof ApiPublicHooksWeeklyDigestRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/set-password': {
      id: '/set-password'
      path: '/set-password'
      fullPath: '/set-password'
      preLoaderRoute: typeof SetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/vault-overview': {
      id: '/app/vault-overview'
      path: '/vault-overview'
      fullPath: '/app/vault-overview'
      preLoaderRoute: typeof AppVaultOverviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/vault': {
      id: '/app/vault'
      path: '/vault'
      fullPath: '/app/vault'
      preLoaderRoute: typeof AppVaultRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/teams': {
      id: '/app/teams'
      path: '/teams'
      fullPath: '/app/teams'
      preLoaderRoute: typeof AppTeamsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/meetings': {
      id: '/app/meetings'
      path: '/meetings'
      fullPath: '/app/meetings'
      preLoaderRoute: typeof AppMeetingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/competitions': {
      id: '/app/competitions'
      path: '/competitions'
      fullPath: '/app/competitions'
      preLoaderRoute: typeof AppCompetitionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/backlog': {
      id: '/app/backlog'
      path: '/backlog'
      fullPath: '/app/backlog'
      preLoaderRoute: typeof AppBacklogRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/agreement': {
      id: '/app/agreement'
      path: '/agreement'
      fullPath: '/app/agreement'
      preLoaderRoute: typeof AppAgreementRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/teams/$teamId': {
      id: '/app/teams/$teamId'
      path: '/$teamId'
      fullPath: '/app/teams/$teamId'
      preLoaderRoute: typeof AppTeamsTeamIdRouteImport
      parentRoute: typeof AppTeamsRoute
    }
    '/app/admin_/usage': {
      id: '/app/admin_/usage'
      path: '/admin/usage'
      fullPath: '/app/admin/usage'
      preLoaderRoute: typeof AppAdminUsageRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin_/team-readiness/': {
      id: '/app/admin_/team-readiness/'
      path: '/admin/team-readiness'
      fullPath: '/app/admin/team-readiness/'
      preLoaderRoute: typeof AppAdminTeamReadinessIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/admin_/team-readiness/$teamId': {
      id: '/app/admin_/team-readiness/$teamId'
      path: '/admin/team-readiness/$teamId'
      fullPath: '/app/admin/team-readiness/$teamId'
      preLoaderRoute: typeof AppAdminTeamReadinessTeamIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/hooks/weekly-digest': {
      id: '/api/public/hooks/weekly-digest'
      path: '/api/public/hooks/weekly-digest'
      fullPath: '/api/public/hooks/weekly-digest'
      preLoaderRoute: typeof ApiPublicHooksWeeklyDigestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/profile-reminders': {
      id: '/api/public/hooks/profile-reminders'
      path: '/api/public/hooks/profile-reminders'
      fullPath: '/api/public/hooks/profile-reminders'
      preLoaderRoute: typeof ApiPublicHooksProfileRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/auto-archive': {
      id: '/api/public/hooks/auto-archive'
      path: '/api/public/hooks/auto-archive'
      fullPath: '/api/public/hooks/auto-archive'
      preLoaderRoute: typeof ApiPublicHooksAutoArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppTeamsRouteChildren {
  AppTeamsTeamIdRoute: typeof AppTeamsTeamIdRoute
}

const AppTeamsRouteChildren: AppTeamsRouteChildren = {
  AppTeamsTeamIdRoute: AppTeamsTeamIdRoute,
}

const AppTeamsRouteWithChildren = AppTeamsRoute._addFileChildren(
  AppTeamsRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppAgreementRoute: typeof AppAgreementRoute
  AppBacklogRoute: typeof AppBacklogRoute
  AppCompetitionsRoute: typeof AppCompetitionsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppMeetingsRoute: typeof AppMeetingsRoute
  AppTeamsRoute: typeof AppTeamsRouteWithChildren
  AppVaultRoute: typeof AppVaultRoute
  AppVaultOverviewRoute: typeof AppVaultOverviewRoute
  AppAdminUsageRoute: typeof AppAdminUsageRoute
  AppAdminTeamReadinessTeamIdRoute: typeof AppAdminTeamReadinessTeamIdRoute
  AppAdminTeamReadinessIndexRoute: typeof AppAdminTeamReadinessIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppAgreementRoute: AppAgreementRoute,
  AppBacklogRoute: AppBacklogRoute,
  AppCompetitionsRoute: AppCompetitionsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppMeetingsRoute: AppMeetingsRoute,
  AppTeamsRoute: AppTeamsRouteWithChildren,
  AppVaultRoute: AppVaultRoute,
  AppVaultOverviewRoute: AppVaultOverviewRoute,
  AppAdminUsageRoute: AppAdminUsageRoute,
  AppAdminTeamReadinessTeamIdRoute: AppAdminTeamReadinessTeamIdRoute,
  AppAdminTeamReadinessIndexRoute: AppAdminTeamReadinessIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SetPasswordRoute: SetPasswordRoute,
  ApiPublicHooksAutoArchiveRoute: ApiPublicHooksAutoArchiveRoute,
  ApiPublicHooksProfileRemindersRoute: ApiPublicHooksProfileRemindersRoute,
  ApiPublicHooksWeeklyDigestRoute: ApiPublicHooksWeeklyDigestRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
