/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppVaultOverviewRouteImport } from './routes/app.vault-overview'
import { Route as AppVaultRouteImport } from './routes/app.vault'
import { Route as AppTeamsRouteImport } from './routes/app.teams'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppBacklogRouteImport } from './routes/app.backlog'
import { Route as AppAgreementRouteImport } from './routes/app.agreement'
import { Route as AppAdminRouteImport } from './routes/app.admin'
import { Route as AppTeamsTeamIdRouteImport } from './routes/app.teams.$teamId'
import { Route as ApiPublicHooksWeeklyDigestRouteImport } from './routes/api/public/hooks/weekly-digest'
import { Route as ApiPublicHooksAutoArchiveRouteImport } from './routes/api/public/hooks/auto-archive'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVaultOverviewRoute = AppVaultOverviewRouteImport.update({
  id: '/vault-overview',
  path: '/vault-overview',
  getParentRoute: () => AppRoute,
} as any)
const AppVaultRoute = AppVaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamsRoute = AppTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppBacklogRoute = AppBacklogRouteImport.update({
  id: '/backlog',
  path: '/backlog',
  getParentRoute: () => AppRoute,
} as any)
const AppAgreementRoute = AppAgreementRouteImport.update({
  id: '/agreement',
  path: '/agreement',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamsTeamIdRoute = AppTeamsTeamIdRouteImport.update({
  id: '/$teamId',
  path: '/$teamId',
  getParentRoute: () => AppTeamsRoute,
} as any)
const ApiPublicHooksWeeklyDigestRoute =
  ApiPublicHooksWeeklyDigestRouteImport.update({
    id: '/api/public/hooks/weekly-digest',
    path: '/api/public/hooks/weekly-digest',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAutoArchiveRoute =
  ApiPublicHooksAutoArchiveRouteImport.update({
    id: '/api/public/hooks/auto-archive',
    path: '/api/public/hooks/auto-archive',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/admin': typeof AppAdminRoute
  '/app/agreement': typeof AppAgreementRoute
  '/app/backlog': typeof AppBacklogRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/teams': typeof AppTeamsRouteWithChildren
  '/app/vault': typeof AppVaultRoute
  '/app/vault-overview': typeof AppVaultOverviewRoute
  '/app/teams/$teamId': typeof AppTeamsTeamIdRoute
  '/api/public/hooks/auto-archive': typeof ApiPublicHooksAutoArchiveRoute
  '/api/public/hooks/weekly-digest': typeof ApiPublicHooksWeeklyDigestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/admin': typeof AppAdminRoute
  '/app/agreement': typeof AppAgreementRoute
  '/app/backlog': typeof AppBacklogRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/teams': typeof AppTeamsRouteWithChildren
  '/app/vault': typeof AppVaultRoute
  '/app/vault-overview': typeof AppVaultOverviewRoute
  '/app/teams/$teamId': typeof AppTeamsTeamIdRoute
  '/api/public/hooks/auto-archive': typeof ApiPublicHooksAutoArchiveRoute
  '/api/public/hooks/weekly-digest': typeof ApiPublicHooksWeeklyDigestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/admin': typeof AppAdminRoute
  '/app/agreement': typeof AppAgreementRoute
  '/app/backlog': typeof AppBacklogRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/teams': typeof AppTeamsRouteWithChildren
  '/app/vault': typeof AppVaultRoute
  '/app/vault-overview': typeof AppVaultOverviewRoute
  '/app/teams/$teamId': typeof AppTeamsTeamIdRoute
  '/api/public/hooks/auto-archive': typeof ApiPublicHooksAutoArchiveRoute
  '/api/public/hooks/weekly-digest': typeof ApiPublicHooksWeeklyDigestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/app/admin'
    | '/app/agreement'
    | '/app/backlog'
    | '/app/dashboard'
    | '/app/teams'
    | '/app/vault'
    | '/app/vault-overview'
    | '/app/teams/$teamId'
    | '/api/public/hooks/auto-archive'
    | '/api/public/hooks/weekly-digest'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/login'
    | '/app/admin'
    | '/app/agreement'
    | '/app/backlog'
    | '/app/dashboard'
    | '/app/teams'
    | '/app/vault'
    | '/app/vault-overview'
    | '/app/teams/$teamId'
    | '/api/public/hooks/auto-archive'
    | '/api/public/hooks/weekly-digest'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/app/admin'
    | '/app/agreement'
    | '/app/backlog'
    | '/app/dashboard'
    | '/app/teams'
    | '/app/vault'
    | '/app/vault-overview'
    | '/app/teams/$teamId'
    | '/api/public/hooks/auto-archive'
    | '/api/public/hooks/weekly-digest'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiPublicHooksAutoArchiveRoute: typeof ApiPublicHooksAutoArchiveRoute
  ApiPublicHooksWeeklyDigestRoute: typeof ApiPublicHooksWeeklyDigestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/vault-overview': {
      id: '/app/vault-overview'
      path: '/vault-overview'
      fullPath: '/app/vault-overview'
      preLoaderRoute: typeof AppVaultOverviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/vault': {
      id: '/app/vault'
      path: '/vault'
      fullPath: '/app/vault'
      preLoaderRoute: typeof AppVaultRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/teams': {
      id: '/app/teams'
      path: '/teams'
      fullPath: '/app/teams'
      preLoaderRoute: typeof AppTeamsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/backlog': {
      id: '/app/backlog'
      path: '/backlog'
      fullPath: '/app/backlog'
      preLoaderRoute: typeof AppBacklogRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/agreement': {
      id: '/app/agreement'
      path: '/agreement'
      fullPath: '/app/agreement'
      preLoaderRoute: typeof AppAgreementRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/teams/$teamId': {
      id: '/app/teams/$teamId'
      path: '/$teamId'
      fullPath: '/app/teams/$teamId'
      preLoaderRoute: typeof AppTeamsTeamIdRouteImport
      parentRoute: typeof AppTeamsRoute
    }
    '/api/public/hooks/weekly-digest': {
      id: '/api/public/hooks/weekly-digest'
      path: '/api/public/hooks/weekly-digest'
      fullPath: '/api/public/hooks/weekly-digest'
      preLoaderRoute: typeof ApiPublicHooksWeeklyDigestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/auto-archive': {
      id: '/api/public/hooks/auto-archive'
      path: '/api/public/hooks/auto-archive'
      fullPath: '/api/public/hooks/auto-archive'
      preLoaderRoute: typeof ApiPublicHooksAutoArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppTeamsRouteChildren {
  AppTeamsTeamIdRoute: typeof AppTeamsTeamIdRoute
}

const AppTeamsRouteChildren: AppTeamsRouteChildren = {
  AppTeamsTeamIdRoute: AppTeamsTeamIdRoute,
}

const AppTeamsRouteWithChildren = AppTeamsRoute._addFileChildren(
  AppTeamsRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppAgreementRoute: typeof AppAgreementRoute
  AppBacklogRoute: typeof AppBacklogRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppTeamsRoute: typeof AppTeamsRouteWithChildren
  AppVaultRoute: typeof AppVaultRoute
  AppVaultOverviewRoute: typeof AppVaultOverviewRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppAgreementRoute: AppAgreementRoute,
  AppBacklogRoute: AppBacklogRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppTeamsRoute: AppTeamsRouteWithChildren,
  AppVaultRoute: AppVaultRoute,
  AppVaultOverviewRoute: AppVaultOverviewRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiPublicHooksAutoArchiveRoute: ApiPublicHooksAutoArchiveRoute,
  ApiPublicHooksWeeklyDigestRoute: ApiPublicHooksWeeklyDigestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
